POST /api/2.5/lots/952ec4e8a05d437892497d1310961cd2/related_processes HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 83
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
X-Access-Token: 4595f9cba04a41cdacda804241fa2bd8
DATA:
{
  "data": {
    "type": "asset", 
    "relatedProcessID": "f6e3a91438fe4091a4ecb28daa3cb957"
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots/952ec4e8a05d437892497d1310961cd2/related_processes/3fcf563ac610489fa92784a21925d215
X-Content-Type-Options: nosniff
{
  "data": {
    "type": "asset", 
    "id": "3fcf563ac610489fa92784a21925d215", 
    "relatedProcessID": "f6e3a91438fe4091a4ecb28daa3cb957"
  }
}

