GET /api/2.5/lots/952ec4e8a05d437892497d1310961cd2 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-02-07-000002", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "d943128ab38546fd84e5ed04a5d7737b"
      }
    ], 
    "lotType": "bargain", 
    "dateModified": "2019-02-07T16:47:37.387539+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:37.372823+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:37.372844+02:00", 
        "id": "bfabdb6721a3490db185ce4af98e6ebf"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "procurementMethodType": "procedure.name", 
        "id": "2b1c95c81b524588b599755ee22e5485"
      }
    ], 
    "date": "2019-02-07T16:47:37.385235+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:37.304927+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "12eba007372d47e2aa42fcf23f0ed644", 
        "decisionOf": "lot"
      }
    ], 
    "id": "952ec4e8a05d437892497d1310961cd2"
  }
}

