GET /api/2.5/lots/86f5b7cf26c4446ca23707c1ed405656 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-03-12-000002", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "9a501623597642f2a58793bc6f2f2a48"
      }
    ], 
    "lotType": "redemption", 
    "dateModified": "2019-03-12T13:28:56.305241+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:56.286818+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:56.286854+02:00", 
        "id": "212eafc66f6d4ef3bd8aac70efc52354"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "procurementMethodType": "reporting", 
        "id": "0253e7e2c9aa4d2c9c9cad1c38ddb88e"
      }
    ], 
    "date": "2019-03-12T13:28:56.302003+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:56.203380+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "8f5a2e677e4a49fda06c850aa0ea98ea", 
        "decisionOf": "lot"
      }
    ], 
    "id": "86f5b7cf26c4446ca23707c1ed405656"
  }
}

