PATCH /api/2.5/lots/86f5b7cf26c4446ca23707c1ed405656/auctions/0253e7e2c9aa4d2c9c9cad1c38ddb88e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 296
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
X-Access-Token: 7e25ecd2e7254c469bb16c87fb5adf51
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "scheduled", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "reporting", 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "0253e7e2c9aa4d2c9c9cad1c38ddb88e", 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

