PATCH /api/2.5/lots/952ec4e8a05d437892497d1310961cd2/auctions/2b1c95c81b524588b599755ee22e5485 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 296
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
X-Access-Token: 4595f9cba04a41cdacda804241fa2bd8
DATA:
{
  "data": {
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "scheduled", 
    "bankAccount": {
      "accountIdentification": [
        {
          "scheme": "accountNumber", 
          "id": "111111-8", 
          "description": "some description"
        }
      ], 
      "bankName": "name of bank"
    }, 
    "procurementMethodType": "procedure.name", 
    "value": {
      "currency": "UAH", 
      "amount": 3000.87, 
      "valueAddedTaxIncluded": true
    }, 
    "id": "2b1c95c81b524588b599755ee22e5485", 
    "guarantee": {
      "currency": "UAH", 
      "amount": 700.87
    }
  }
}

