GET /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/2.5/lots?offset=2019-02-07T16%3A47%3A37.598774%2B02%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots?offset=2019-02-07T16%3A47%3A37.598774%2B02%3A00", 
    "offset": "2019-02-07T16:47:37.598774+02:00"
  }, 
  "data": [
    {
      "id": "952ec4e8a05d437892497d1310961cd2", 
      "dateModified": "2019-02-07T16:47:37.598774+02:00"
    }
  ]
}

