GET /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "next_page": {
    "path": "/api/2.5/lots?offset=2019-03-12T13%3A28%3A56.550936%2B02%3A00", 
    "uri": "http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots?offset=2019-03-12T13%3A28%3A56.550936%2B02%3A00", 
    "offset": "2019-03-12T13:28:56.550936+02:00"
  }, 
  "data": [
    {
      "id": "86f5b7cf26c4446ca23707c1ed405656", 
      "dateModified": "2019-03-12T13:28:56.550936+02:00"
    }
  ]
}

