GET /api/2.5/lots/d27e2f7197bd45e8aebfe4f5dc3e3db2 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "lotID": "UA-LR-DGF-2019-03-12-000002", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "eddda59bfe6e4316a41580e547da271f"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "redemption", 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:57.910939+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "457a3a9afd614e5695cb42127c0ab0bb", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "10e8427741c04083a58fe213ca6a7005", 
        "decisionDate": "2019-03-12T13:28:58.181645+02:00", 
        "decisionID": "11111-4-5", 
        "id": "51bf01fdf0e740d3a1467e26cd4aefe1", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-03-12T13:28:58.388932+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "reporting", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "4108d6a55abd4c52a3323f56327f2d37", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-03-12T13:28:58.388596+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:57.915305+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:57.915325+02:00", 
        "id": "0ba040f4ec7243579270497975ba2152"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "57008d55778b44f99db68faab5c5c17a", 
        "relatedProcessID": "36483bc5df2a42c3aecba97e5b2d8387"
      }
    ], 
    "id": "d27e2f7197bd45e8aebfe4f5dc3e3db2"
  }
}

