POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 233
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:37.304927+02:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "lotType": "bargain", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "relatedProcessID": "6e66626e86434027824ed44b1052c89e"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots/7e8cf4747ea34a78a636238b61fa81f9
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "799c19cdbe124f65ba4257a144565643", 
    "token": "cdf90788487842fca203f6452befbead"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-02-07-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "ec569f8d7868402294181f488dc10ecc"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:37.304927+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "a44a07454daa4a32b7791730c010dfc4", 
        "decisionOf": "lot"
      }
    ], 
    "lotType": "bargain", 
    "dateModified": "2019-02-07T16:47:37.347352+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:37.331485+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:37.331505+02:00", 
        "id": "6318a92e8d014647a4c3f2efd83fdddc"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "procurementMethodType": "procedure.name", 
        "id": "386cb0e3b48c439085b0e7c74e75212f"
      }
    ], 
    "date": "2019-02-07T16:47:37.345356+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "335e0167955e47db89672e8cd18b97ad", 
        "relatedProcessID": "6e66626e86434027824ed44b1052c89e"
      }
    ], 
    "id": "7e8cf4747ea34a78a636238b61fa81f9"
  }
}

