POST /api/2.5/lots?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 236
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:56.203380+02:00", 
        "decisionID": "initialDecisionID"
      }
    ], 
    "lotType": "redemption", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "relatedProcessID": "13aca930afb34ab0ab78838811213aac"
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json
Location: http://lb.api-sandbox.registry.ea2.openprocurement.net/api/2.5/lots/b5caff0875214c02bf220302786d38da
X-Content-Type-Options: nosniff
{
  "access": {
    "transfer": "08f0ebbddd9c46749cc6f8b1370ed831", 
    "token": "9d9a68e7046c4a69a55b5343dc886080"
  }, 
  "data": {
    "status": "draft", 
    "lotID": "UA-LR-DGF-2019-03-12-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "f2205eaf4dbb458885e8cd7aa5f1a2d9"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:56.203380+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "6c6b3f8570104128b3fc28ca348207c2", 
        "decisionOf": "lot"
      }
    ], 
    "lotType": "redemption", 
    "dateModified": "2019-03-12T13:28:56.248759+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:56.231779+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:56.231801+02:00", 
        "id": "7ceb59e74f4746a185a20fb231ec7ba0"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "procurementMethodType": "reporting", 
        "id": "eb19155463a542f9ae34ee6f9dde84e6"
      }
    ], 
    "date": "2019-03-12T13:28:56.246941+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "cbed9e6a264142a78cface1e257d82ce", 
        "relatedProcessID": "13aca930afb34ab0ab78838811213aac"
      }
    ], 
    "id": "b5caff0875214c02bf220302786d38da"
  }
}

