GET /api/2.5/lots/51d60506f53f402d8bc77238467cde03 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "sold", 
    "lotID": "UA-LR-DGF-2019-03-12-000004", 
    "contracts": [
      {
        "status": "complete", 
        "type": "yoke", 
        "id": "8322e2585cb24dcc86ed786da2f47ef9"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "redemption", 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:59.930391+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "de4eacd19bb1451582d2ea16a67a0c09", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "11111111111111111111111111111111", 
        "decisionDate": "2019-03-12T13:29:00.173235+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "4c195f3b460f47cf824f936c057f38f3", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-03-12T13:29:00.819322+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:59.937608+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:59.937632+02:00", 
        "id": "78ae301e19c14332b4d3aa9ae75069e7"
      }
    ], 
    "auctions": [
      {
        "status": "complete", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "reporting", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "4b5a9cb7e8f24369a92f34dbfef2f761", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-03-12T13:29:00.818841+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "ddc8904d592e4bd2b378fa01bfae1b01", 
        "relatedProcessID": "93afe63d2f254db3b81d399803068a44"
      }
    ], 
    "id": "51d60506f53f402d8bc77238467cde03"
  }
}

