GET /api/2.5/lots/c1168946bacd44f0a4790ea843aaea06 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "sold", 
    "lotID": "UA-LR-DGF-2019-02-07-000004", 
    "contracts": [
      {
        "status": "complete", 
        "type": "yoke", 
        "id": "dab2e6bbe19c4f4fbad7958e18974537"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "bargain", 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:40.313769+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "317473503c0b40aa8c56e386dcf60548", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "11111111111111111111111111111111", 
        "decisionDate": "2019-02-07T16:47:40.560206+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "edd30d079de2451383cab52e89f4ef88", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-02-07T16:47:41.073121+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:40.318367+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:40.318387+02:00", 
        "id": "025df11f7c13460480bc65cdc53c06d3"
      }
    ], 
    "auctions": [
      {
        "status": "complete", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "procedure.name", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "2afa551c6376416eb122d7e07ffd7489", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-02-07T16:47:41.072889+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "973beb778de54bfd972e79623373f07b", 
        "relatedProcessID": "4260d3345cf94fc6bd0cd058e5706360"
      }
    ], 
    "id": "c1168946bacd44f0a4790ea843aaea06"
  }
}

