PATCH /api/2.5/lots/86f5b7cf26c4446ca23707c1ed405656?acc_token=7e25ecd2e7254c469bb16c87fb5adf51 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 39
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "pending.deleted"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending.deleted", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "lotID": "UA-LR-DGF-2019-03-12-000002", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "9a501623597642f2a58793bc6f2f2a48"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "redemption", 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:56.203380+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "8f5a2e677e4a49fda06c850aa0ea98ea", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "652ea7afe73d4e6bb05df61e11753fd9", 
        "decisionDate": "2019-03-12T13:28:56.853351+02:00", 
        "decisionID": "11111-4-5", 
        "id": "8f7291b82c6244e08bc12842c656d666", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-03-12T13:28:57.391852+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "reporting", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "0253e7e2c9aa4d2c9c9cad1c38ddb88e", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-03-12T13:28:57.391507+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:56.286818+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:56.286854+02:00", 
        "id": "212eafc66f6d4ef3bd8aac70efc52354"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "author": "lot_owner", 
        "title": "укр.doc", 
        "url": "http://localhost/get/0daf251e8f744e8a91b321e6e0861b93?KeyID=172d32c8&Signature=Fc9VACppAhMOnwBCVzVWlgz5wiYzYqSIgdj08J59LAvVnn6%2FRHO4uaf05ji1uZsayl5zJWnDsO902Vg7DY9nDA%253D%253D", 
        "format": "application/msword", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:57.221917+02:00", 
        "documentType": "cancellationDetails", 
        "dateModified": "2019-03-12T13:28:57.221982+02:00", 
        "id": "0ec306f01d3746af89d8d090f6b10273"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "ed95cd7dfabd4f3da3818ae742d14c36", 
        "relatedProcessID": "b014dd89b9c94e30964a8ce6dcc68a91"
      }
    ], 
    "id": "86f5b7cf26c4446ca23707c1ed405656"
  }
}

