GET /api/2.5/lots/32b717c57608491cacdc223260f12ba4 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "invalid", 
    "lotID": "UA-LR-DGF-2019-02-07-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "e2033c512e794589a859670d1411594f"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:38.187837+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "55d62d2198d7403d86bdc354328a0f0d", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "11111111111111111111111111111111", 
        "decisionDate": "2019-02-07T16:47:38.434294+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "cdd5aa1018454e5aa63aa644ee1bdec8", 
        "decisionOf": "asset"
      }
    ], 
    "lotType": "bargain", 
    "dateModified": "2019-02-07T16:47:38.544987+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:38.195428+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:38.195464+02:00", 
        "id": "c0c956caa99f4baa82b63705e4f783cb"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "procedure.name", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "748d5879b33848eca68ee9560d7fc7a2", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-02-07T16:47:38.544803+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "5a1d56c36b4049f3b2f5581ac10c3fb4", 
        "relatedProcessID": "7a0dc066401e4eaebae60cdc7e0d6008"
      }
    ], 
    "id": "32b717c57608491cacdc223260f12ba4"
  }
}

