GET /api/2.5/lots/3596e6588a2e44bcb330c0d384269a8f HTTP/1.0
Authorization: Basic Y29udm95Og==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending.dissolution", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "lotID": "UA-LR-DGF-2019-02-07-000003", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "cancelled", 
        "type": "yoke", 
        "id": "7f8c98e55ad3420fbad2fcf75e8790f3"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "bargain", 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:39.326339+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "6d8ef55fb62543e38db8c501f7d81e16", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "ca2ce2dbf0b149f6893d3b7010991f4b", 
        "decisionDate": "2019-02-07T16:47:39.549328+02:00", 
        "decisionID": "11111-4-5", 
        "id": "46426b71ae4949f7aaf3ce2d9af94cd9", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-02-07T16:47:40.126713+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "cancelled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "procedure.name", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "78c2b3e9414f4c0895796e291a71f447", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-02-07T16:47:40.126352+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:39.331374+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:39.331396+02:00", 
        "id": "c5c0f9879b394ed0a6a278a7e3aa7b07"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "66682099593d40149e6fafd02a4decb1", 
        "relatedProcessID": "972e8bc3ca744f05b206acc360f5a60f"
      }
    ], 
    "id": "3596e6588a2e44bcb330c0d384269a8f"
  }
}

