GET /api/2.5/lots/66e9159dddea4e3d84e95d9889773501 HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "pending", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "lotID": "UA-LR-DGF-2019-02-07-000002", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "275e7520ba04496c884a3ae652820f3b"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "bargain", 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:38.582398+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "5d33cfc51fb74d86ab2cbead6343130f", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "ca0398ab105c4cadb810e6dbf71b69d2", 
        "decisionDate": "2019-02-07T16:47:38.851176+02:00", 
        "decisionID": "11111-4-5", 
        "id": "7a6541ce40714dd0bda4f4c5198dbdab", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-02-07T16:47:39.013180+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "procedure.name", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "0958db043b944a3eb437991d2d4cf266", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-02-07T16:47:39.012947+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:38.587368+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:38.587390+02:00", 
        "id": "4c3a6d9ed09c4f7db01f8aea9f47914c"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "bfb74347e6c94d149c8eccd7a5b34b32", 
        "relatedProcessID": "f25630b3b44e4fe28406b67de57aa29d"
      }
    ], 
    "id": "66e9159dddea4e3d84e95d9889773501"
  }
}

