GET /api/2.5/lots/3def48a27483417ab51f7d8431f8b11a HTTP/1.0
Authorization: Basic Y29uY2llcmdlOg==
Host: lb.api-sandbox.registry.ea2.openprocurement.net

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "invalid", 
    "lotID": "UA-LR-DGF-2019-03-12-000001", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "d253e1686aec4f94a626bd58a060a77a"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:57.486294+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "f8381939fe7b48259d02e3be71c08d5c", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "11111111111111111111111111111111", 
        "decisionDate": "2019-03-12T13:28:57.749143+02:00", 
        "decisionID": "decisionAssetID", 
        "id": "a52dc53311554f22a57e5443cce8e62d", 
        "decisionOf": "asset"
      }
    ], 
    "lotType": "redemption", 
    "dateModified": "2019-03-12T13:28:57.873564+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:57.491799+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:57.491824+02:00", 
        "id": "7a4b1f971b0b4aa2a4b3fca3e6848946"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "reporting", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "55e279b4447a424ca952cffffa355b46", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-03-12T13:28:57.873301+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "427ba4c528d44e41a69c0dafb253e05d", 
        "relatedProcessID": "e59cf6de07ea4220a9d2ed990df96b77"
      }
    ], 
    "id": "3def48a27483417ab51f7d8431f8b11a"
  }
}

