PATCH /api/2.5/lots/952ec4e8a05d437892497d1310961cd2?acc_token=4595f9cba04a41cdacda804241fa2bd8 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 36
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "verification"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "verification", 
    "lotID": "UA-LR-DGF-2019-02-07-000002", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "d943128ab38546fd84e5ed04a5d7737b"
      }
    ], 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:37.304927+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "12eba007372d47e2aa42fcf23f0ed644", 
        "decisionOf": "lot"
      }
    ], 
    "lotType": "bargain", 
    "dateModified": "2019-02-07T16:47:37.598774+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:37.372823+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:37.372844+02:00", 
        "id": "bfabdb6721a3490db185ce4af98e6ebf"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "procedure.name", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "2b1c95c81b524588b599755ee22e5485", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-02-07T16:47:37.598550+02:00", 
    "relatedProcesses": [
      {
        "type": "asset", 
        "id": "3fcf563ac610489fa92784a21925d215", 
        "relatedProcessID": "f6e3a91438fe4091a4ecb28daa3cb957"
      }
    ], 
    "id": "952ec4e8a05d437892497d1310961cd2"
  }
}

