PATCH /api/2.5/lots/c26137d9a1424fd8a9cd313f7502b48e?acc_token=4497cce23006422c81a27a6a1f51e393 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 38
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "active.salable"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "active.salable", 
    "lotHolder": {
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Власник лоту"
    }, 
    "lotID": "UA-LR-DGF-2019-03-12-000003", 
    "description": "Нежитлове приміщення для збереження насіння", 
    "title": "Нежитлове приміщення", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "3a939cb72daf4374846d6ef112122e40"
      }
    ], 
    "items": [
      {
        "registrationDetails": {
          "status": "unknown"
        }, 
        "description": "футляри до державних нагород", 
        "classification": {
          "scheme": "CPV", 
          "description": "Description", 
          "id": "73110000-6"
        }, 
        "additionalClassifications": [
          {
            "scheme": "UA-EDR", 
            "description": "папір і картон гофровані, паперова й картонна тара", 
            "id": "111111-4"
          }
        ], 
        "address": {
          "countryName": "Ukraine"
        }, 
        "id": "0", 
        "unit": {
          "code": "code"
        }, 
        "quantity": 5.0001
      }
    ], 
    "lotType": "redemption", 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:58.772651+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "3d1881310a034b9b8815b310c5b0937b", 
        "decisionOf": "lot"
      }, 
      {
        "relatedItem": "a302872674f24bf490868f2ec11cb4b7", 
        "decisionDate": "2019-03-12T13:28:59.004934+02:00", 
        "decisionID": "11111-4-5", 
        "id": "6fabec1561294bca9e473e55f1e04176", 
        "decisionOf": "asset"
      }
    ], 
    "dateModified": "2019-03-12T13:28:59.350022+02:00", 
    "owner": "broker", 
    "lotCustodian": {
      "contactPoint": {
        "name": "Сергій", 
        "email": "segiy@mail.com"
      }, 
      "identifier": {
        "scheme": "AE-ADCD", 
        "id": "11111-4"
      }, 
      "name": "Зберігач лоту", 
      "address": {
        "countryName": "Україна"
      }
    }, 
    "auctions": [
      {
        "status": "scheduled", 
        "bankAccount": {
          "accountIdentification": [
            {
              "scheme": "accountNumber", 
              "id": "111111-8", 
              "description": "some description"
            }
          ], 
          "bankName": "name of bank"
        }, 
        "procurementMethodType": "reporting", 
        "value": {
          "currency": "UAH", 
          "amount": 3000.87, 
          "valueAddedTaxIncluded": true
        }, 
        "id": "b52ea692ee6e4a31bf5570d622a8fd6e", 
        "guarantee": {
          "currency": "UAH", 
          "amount": 700.87
        }
      }
    ], 
    "date": "2019-03-12T13:28:59.349783+02:00", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:58.779248+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:58.779272+02:00", 
        "id": "e9068a19ed4b4d509a3c58c464c90469"
      }
    ], 
    "relatedProcesses": [
      {
        "identifier": "UA-AR-P-2018-08-17-000002-1", 
        "type": "asset", 
        "id": "512434358ee849d7a7637d2d5503b6fa", 
        "relatedProcessID": "1076a04e6874433ea474b8c59bf99f44"
      }
    ], 
    "id": "c26137d9a1424fd8a9cd313f7502b48e"
  }
}

