PATCH /api/2.5/lots/51885c40fd69474087424adb80403ac3?acc_token=fadbe1f5c36c4b0db64b6a3a0621f22f HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 53
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "description": "Lot description modified"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2019-03-12-000003", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "226bc4dcebc549c8998b1c1ef53ecb7c"
      }
    ], 
    "lotType": "redemption", 
    "dateModified": "2019-03-12T13:28:56.730774+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-03-12T13:28:56.629617+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-03-12T13:28:56.629663+02:00", 
        "id": "54fd16b06e7941809a2e01f72ef85ecd"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "procurementMethodType": "reporting", 
        "id": "f8709898a0cd459cac6935a20847d6b8"
      }
    ], 
    "date": "2019-03-12T13:28:56.730490+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-03-12T13:28:56.203380+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "7bc35bca8f3b46b4832f1d29dd5ff664", 
        "decisionOf": "lot"
      }
    ], 
    "id": "51885c40fd69474087424adb80403ac3"
  }
}

