PATCH /api/2.5/lots/8fcac6a951c243c1aa3b24aa65042c8b?acc_token=2e30256a2e7047489ae8c15c0a3c1c78 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: lb.api-sandbox.registry.ea2.openprocurement.net
DATA:
{
  "data": {
    "status": "composing"
  }
}

Response: 200 OK
Content-Type: application/json
X-Content-Type-Options: nosniff
{
  "data": {
    "status": "composing", 
    "lotID": "UA-LR-DGF-2019-02-07-000003", 
    "contracts": [
      {
        "status": "scheduled", 
        "type": "yoke", 
        "id": "b2692a10434e4c3e8815c2b75758fd6b"
      }
    ], 
    "lotType": "bargain", 
    "dateModified": "2019-02-07T16:47:37.714755+02:00", 
    "owner": "broker", 
    "documents": [
      {
        "description": "Перелік та реквізити авторизованих електронних майданчиків (найменування установи банку, її адреса та номери рахунків, відкритих для внесення гарантійного внеску, реєстраційного внеску)", 
        "title": "Перелік та реквізити авторизованих електронних майданчиків", 
        "url": "https://prozorro.sale/info/elektronni-majdanchiki-ets-prozorroprodazhi-cbd2", 
        "documentOf": "lot", 
        "datePublished": "2019-02-07T16:47:37.645177+02:00", 
        "documentType": "x_PlatformLegalDetails", 
        "dateModified": "2019-02-07T16:47:37.645197+02:00", 
        "id": "4267cd9925234795a2faef5dc22586d2"
      }
    ], 
    "auctions": [
      {
        "status": "scheduled", 
        "procurementMethodType": "procedure.name", 
        "id": "56949f3c5bc34297b4174595e1c3cbd2"
      }
    ], 
    "date": "2019-02-07T16:47:37.714561+02:00", 
    "decisions": [
      {
        "decisionDate": "2019-02-07T16:47:37.304927+02:00", 
        "decisionID": "initialDecisionID", 
        "id": "814f237bce194d6da66245108009feb8", 
        "decisionOf": "lot"
      }
    ], 
    "id": "8fcac6a951c243c1aa3b24aa65042c8b"
  }
}

